version: "3"
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - "8082:8082"
    volumes:
      - ./server:/usr/src/app
    
  client:
    build: 
      context: ./productstatus
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./productstatus:/usr/src/app

    