version: "3"
services:
  server:
    build:
     context: ./server
     dockerfile: Dockerfile
    ports:
      - "8082:8082"
    volumes:
      - ./server:/usr/src/app  # Mount project files
  

  client:
    build:
      context: ./productstatus
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    volumes:
      - ./productstatus:/usr/src/app
      
