
# To add record manually by date
GET http://localhost:8082/paint/savetoexcel/2025-03-06
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NDU1YjQ5ODQ3OTYzOGQzMTk0MjMxN2MiLCJpYXQiOjE3NDA2NjUzODF9.u5nQDFvdk1YDAcY7zp0RIfnfu1FSRBv35Nyf4QPAqfk



